config/routes.rb
Rails.application.routes.draw do
  root 'tweets#index'
  get 'tweets' => "tweets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
require 'twitter'

class Tweet < ApplicationRecord
  def self.client
    Twitter::REST::Client.new do |config|
      config.consumer_key = ENV["TF_TWITTER_CONSUMER_KEY"]
      config.consumer_secret = ENV["TF_TWITTER_CONSUMER_SECRET"]
      config.access_token = ENV["TF_TWITTER_ACCESS_TOKEN"]
      config.access_token_secret = ENV["TF_TWITTER_ACCESS_TOKEN_SECRET"]
    end
  end

  @@client = client

  def self.search query, how_many = 25, options = {result_type: 'recent'}
    @@tweets = @@client.search(query, options).take(how_many).collect do |tweet|
      tweet
    end
  end

  def self.raw
    @@raw = @@tweets.collect do |tweet|
      tweet.to_h
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    unless params[:num]
      params[:num] = "25"
    end

    if params[:query]
      @tweets = Tweet.search(params[:query], params[:num].to_i)
      @raw = Tweet.raw
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
require 'awesome_print'

module TweetsHelper
  def linkify html
    html.gsub(%r{https?://[^\s<]+}) do |url|
      "<a href='#{url}' rel='nofollow' target='_blank'>#{url}</a>"
    end.gsub(%r{\@\w+}) do |sn|
      sn[0] = ''
      "<a href='https://twitter.com/#{sn}'>@#{sn}</a>"
    end
  end

  def color_hashtag html
    html.gsub(%r{(?<=\s|\b|^)\#\w+(?=\b)}) do |h|
      "<span class='hashtag'>#{h}</span>"
    end
  end

  def prettify_hash raw
    raw.ai(html: true, plain: true, index: false, indent: 2)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Search for Tweets and Facebook Statuses</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <a href="https://github.com/styd/stfs"><img style="position: absolute; top: 0; right: 0; border: 0; z-index: 9999;" src="https://camo.githubusercontent.com/652c5b9acfaddf3a9c326fa6bde407b87f7be0f4/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f6f72616e67655f6666373630302e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_right_orange_ff7600.png"></a>

    <%= yield %>
  </body>
</html>

app/views/tweets/_footer.html.erb
<script>
  $(document).ready(function() {
  });
</script>

<footer>
  <p class="tech">
    <small>
      Technology: <i>Ruby</i>, <i>Rails</i>, <i>Twitter API</i>, <i>RSpec</i>,
      <i>Capybara</i>, <i>Bootstrap</i>, <i>Javascript</i>, <i>JQuery</i>,
      <i>HTML5</i>, <i>CSS3</i>, <i>SCSS</i>
    </small>
  </p>
  <p id="author">
    made with <span id="love">♥</span> by <a href="https://github.com/styd">Adrian Setyadi</a>
  </p>
</footer>

app/views/tweets/_header.html.erb
<form action="<%= tweets_path %>" method="get" id="search-form" class="pusher">
  <div>
    <%= text_field_tag :query, params[:query], id: "query", placeholder: "Find tweets" %>
    <%= button_tag(type: "submit", id: "submit", name: nil) do %>
      Find
    <% end %>
    first
    <%= number_field_tag :num, params[:num], id: "num", min: 1, max: 300 %>
    tweets
  </div>
</form>

app/views/tweets/index.html.erb
<div class="container-fluid viewport">
  <div class="row search">
    <div class="col-xs-12 col-md-6 col-md-offset-3">
      <%= render 'header' %>
    </div>
  </div>

  <div class="row result">
    <div class="col-xs-12 col-md-6 col-md-offset-3">
    <% if @tweets %>
      <strong>Search Results:</strong>
      <button id="toggle" style="float: right;">RAW</button>
      <div id="cooked">
        <% @tweets.each do |tweet| %>
          <div class="a-tweet" style="cursor: pointer;"
            onclick="openTweet('<%= tweet.user.screen_name %>', '<%= tweet.id %>');">

            <div class="profile-image">
              <a href="<%= tweet.user.profile_image_url_https.to_s.gsub(/_normal/, '') %>" rel="nofollow" target="_blank">
                <img src="<%= tweet.user.profile_image_url_https %>" alt="<%= tweet.user.name %>'s profile image">
              </a>
            </div>
            <div class="tweet-content">
              <span class="name">
                <a href="https://twitter.com/<%= tweet.user.screen_name %>" rel="nofollow" target="_blank">
                  <%= tweet.user.name %>
                </a>
              </span>
              ( <span class="screen-name">
                <a href="https://twitter.com/<%= tweet.user.screen_name %>" rel="nofollow" target="_blank">
                  @<%= tweet.user.screen_name %>
                </a>
              </span> )
              <span class="created-at"><%= tweet.created_at.in_time_zone(tweet.user.time_zone)
                .localtime.strftime("on <i>%a, %b %d, %Y</i> at <i>%H:%M:%S</i>").html_safe %></span>
              <div class="text"><%= simple_format(color_hashtag(linkify(tweet.text))) %></div>
              <small class="from pull-right">tweeted from <%= tweet.source.html_safe %></small>
            </div>

          </div>
        <% end %>
      </div>

      <div id="raw">
        <%= prettify_hash(@raw) %>
      </div>

      <%= render 'footer' %>

    <% end %>
    </div>
  </div>
</div>